import os 
import re 
import sys 
from sys import argv 

#Conserved sequnces 
cons=open(sys.argv[1], 'r').readlines()

###GC/AC/AG Conent###

X=input('Specify AC,GC,AG?: ')

dict={}

for index, line in  enumerate(cons):
	if (line.startswith('>')):
		header=cons[index]
		pos=header.split(' ')[0]
		seq=cons[index+1]
		A=seq.count(X[0])
		B=seq.count(X[1])
		AB=(A+B)/len(seq)
		dict[pos]=AB


#for i in dict.keys():
#	print(i, dict[i])		
		
###Spread of GC, AC, AG content###
#Generate a figure to show where spread of GC content across cnserved regions
#Use location info from the conserverd regions FASTAs to generate figure

for i in dict.keys():
	if (dict[i]<=0.25):
		print('Low')
	if (dict[i]>=0.75):
		print('High')
	if (dict[i]<0.75 and dict[i]>0.25):
		print('Intermediate')

###Location in Genome###	
#Figure to show spread of stable regions 
#Location info is in header of conserved regions 
#Generate count of how many conserved regions have the same location - use in barplot 

#for i in os.lisdir('filepath_to_all_conserverd_regions_file')
#	dict={}
#	count=0
#	file=open('i', 'r').readlines()
#	for index, line in enumerate(file):
#		if (line.startswith('>')):
#			header=file[index]
#			pos=header.split(' ')[1]
			

####Gene####
#meta=open('sequence.meta', 'r').readlines()

#for i in meta:
#	lines=[i.rstrip().split('\t') if i!='#']
#	start=[lines[4] if (lines[3]=='gene')]
#	end=[lines[5] if (lines[3]=='gene')]
#	
		
			
